### ISSUE TITLE
Cannot read property 'length' of undefined (reject.js:58)

### ISSUE THREAD

**Issue by digitalgoodsprovider** [Fi3/bitcore-p2p#1]
/var/sentora/hostdata/zadmin/node_modules/bitcore-p2p-fix-malformedMessages-86/lib/messages/commands/reject.js:58
  bw.writeVarintNum(this.message.length);
                                ^

TypeError: Cannot read property 'length' of undefined
    at RejectMessage.getPayload (/var/sentora/hostdata/zadmin/node_modules/bitcore-p2p-fix-malformedMessages-86/lib/messages/commands/reject.js:58:33)
    at RejectMessage.Message.toBuffer.Message.serialize (/var/sentora/hostdata/zadmin/node_modules/bitcore-p2p-fix-malformedMessages-86/lib/messages/message.js:30:22)
    at Peer.sendMessage (/var/sentora/hostdata/zadmin/node_modules/bitcore-p2p-fix-malformedMessages-86/lib/peer.js:194:29)
    at Peer._readMessage (/var/sentora/hostdata/zadmin/node_modules/bitcore-p2p-fix-malformedMessages-86/lib/peer.js:230:12)
    at Socket.<anonymous> (/var/sentora/hostdata/zadmin/node_modules/bitcore-p2p-fix-malformedMessages-86/lib/peer.js:167:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

Happens about once every 2 days ... so it's a pretty regular thing that still kills an app!

**Comment by digitalgoodsprovider** [comment]
switched code to bcoin bit-core==obsolete
